const SAMPLE_PARAGRAPHS = [
  "The morning air carried a faint chill, the kind that settles in just before the season turns. People moved along the sidewalk at their usual pace, some clutching paper cups, others staring down at their phones without breaking stride. A dog barked somewhere behind a fence, and a bus hissed to a stop at the corner, letting out a handful of passengers who scattered in different directions. It was an ordinary day by every measure, the sort that leaves no particular impression once it has passed. Still, there was something pleasant about the routine of it all, the predictable rhythm of a place going about its business, unbothered by anything in particular.",
  "The domestication of honeybees dates back at least four thousand years, with early records of managed hives appearing in Egyptian tomb paintings and Mesopotamian tablets. Beekeepers in these societies understood that colonies would occupy almost any enclosed cavity, so they built hives from hollow logs, woven straw, and fired clay pipes stacked in long rows. Harvesting honey usually meant destroying part of the comb, and in many cases the entire colony, since the movable frame had not yet been invented. That changed in the nineteenth century, when observers determined the precise spacing bees leave between combs and used it to design hives that could be opened and inspected without damage. The innovation made large scale apiculture practical and remains the basis for most commercial hive designs in use today.",
  "The invention of the printing press in the mid fifteenth century changed how information moved through Europe. Before Johannes Gutenberg introduced movable type, books were copied by hand, a process that could take a scribe months or even years to complete for a single volume. As a result, texts were expensive and rare, held mostly in monasteries and the libraries of wealthy patrons. Printed books lowered the cost of production dramatically, and within fifty years presses had been established in hundreds of cities. The wider availability of printed material contributed to rising literacy rates, the standardization of regional languages, and the rapid spread of new scientific and religious ideas. Historians often point to this period as a turning point in the development of modern communication.",
  "The common house sparrow is one of the most widely distributed birds in the world, found on every continent except Antarctica. Originally native to Europe and parts of Asia, it spread rapidly after being introduced to North America in the 1850s, when a small number of birds released in Brooklyn established a population that expanded across the continent within a few decades. Sparrows thrive in urban and agricultural areas because they eat a varied diet of seeds, grains, and insects, and they nest readily in building crevices, signs, and streetlights. Despite this adaptability, populations in several European cities have declined sharply since the 1980s. Researchers have proposed a number of explanations, including reduced insect availability for chicks, changes in building design that eliminate nesting cavities, and increased air pollution, though no single cause has been confirmed.",
  "The postal system in the nineteenth century transformed how ordinary people communicated across long distances. Before standardized rates were introduced, the cost of sending a letter often fell to the recipient, and prices varied according to distance and the number of sheets used. Reformers argued that a single low rate, paid in advance by the sender, would encourage far greater use of the mail and ultimately increase revenue. When Britain adopted the penny post in 1840, the volume of letters more than doubled within a few years. Other countries watched the experiment closely and adopted similar systems over the following decades, laying the groundwork for the international postal agreements that still govern cross border mail today.",
  "I grew up in a small town where the same three streets held everything I thought mattered: the school, the grocery store, and the diner where my mother worked weekends. Summers were long and mostly empty, which at the time felt like a punishment and now feels like a gift. I read whatever I could find, rode my bike until the sun went down, and assumed the rest of the world was somewhere far away, waiting for me to be old enough to reach it. When I finally left for college, I was surprised to find that I missed the quiet more than I expected. It took me a few years to understand that leaving a place does not mean you stop carrying it around. These days I live in a city, surrounded by noise I mostly like, and I still catch myself listening for crickets at night.",
  "I woke up earlier than I meant to, which is unusual for me, and I spent a while just lying there listening to the sound of traffic outside. Eventually I got up and made coffee, mostly out of habit rather than any real desire for it. The kitchen was cold, so I stood by the window with my hands wrapped around the mug and watched a neighbor walk his dog past the same row of parked cars he passes every morning. I thought about all the things I had been meaning to do that week and decided none of them were urgent enough to start before eight. It was a slow morning, and I did not mind that at all.",
  // "hello i am a testing string"
]


export function getRandomParagraph() {
  return SAMPLE_PARAGRAPHS[Math.floor(Math.random() * SAMPLE_PARAGRAPHS.length)].toLocaleLowerCase()
}